//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jabil
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveGRN
    {
        public int ID { get; set; }
        public string GRN { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string PartNumber { get; set; }
        public string Machine { get; set; }
    }
}
