//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jabil
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LiveGPI> LiveGPIs { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<CustomerOfUser> CustomerOfUsers { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Record> Records { get; set; }
        public virtual DbSet<RecordData> RecordDatas { get; set; }
        public virtual DbSet<GrnOfEpc> GrnOfEpcs { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<FXReader> FXReaders { get; set; }
        public virtual DbSet<MachineOfCustomer> MachineOfCustomers { get; set; }
        public virtual DbSet<LiveTag> LiveTags { get; set; }
        public virtual DbSet<ActiveGRN> ActiveGRNs { get; set; }
    }
}
