//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jabil
{
    using System;
    using System.Collections.Generic;
    
    public partial class FXReader
    {
        public string FXReaderID { get; set; }
        public string IPAddress { get; set; }
        public string FXReaderName { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyAt { get; set; }
        public string ModifyBy { get; set; }
        public string AuthorizationCode { get; set; }
        public Nullable<int> MachineID { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
