//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jabil
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineOfCustomer
    {
        public int CusID { get; set; }
        public int MachineID { get; set; }
        public string CusName { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
