//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jabil
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Record()
        {
            this.RecordDatas = new HashSet<RecordData>();
        }
    
        public int RecordID { get; set; }
        public string RecordType { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string Owner { get; set; }
        public string Machine { get; set; }
        public string Assembly { get; set; }
        public string Setup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordData> RecordDatas { get; set; }
    }
}
